language: python

python:
    - "3.6"
    - "3.7"

install:
    - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH="$HOME/miniconda/bin:$PATH"
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda info -a
    
    - conda create --yes -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy matplotlib pandas pillow pytest nose coveralls pytest-cov
    - source activate test-environment
    - python setup.py install

script:
    - py.test -v tests --cov coastlib

after_success:
    - coveralls
